config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  # サイトの使い方ページ
  get 'about', to: 'toppages#about'

  # ログイン機能
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # 簡単ログイン
  post 'easy_login', to: 'guest_sessions#test'

  # 勉強を始める
  get 'start', to: 'records#new'

  resources :users, only: %i[index show new edit create update] do
    member do
      get :followings
      get :followers
      get :likes
      get :records
    end
  end

  resources :microposts, only: %i[index create destroy] do
    member do
      get :following_posts
    end
  end

  resources :records, only: %i[index show new edit create] do
    member do
      get :stop
      get :restart
      get :finish
      get :result
    end
  end

  resources :supports, only: %i[create destroy] do
    collection do
      get :supporters
    end
  end

  resources :relationships, only: %i[create destroy]
  resources :favorites, only: %i[create destroy]
  resource :password, only: %i[show edit update]
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 10 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  validates :gender, presence: true
  validates :age, presence: true

  attr_accessor :current_password
  validates :new_password, presence: { if: :current_password }

  has_secure_password
  has_one_attached :profile_image

  mount_uploader :img, ImgUploader

  has_many :microposts, dependent: :destroy
  has_many :records, dependent: :destroy

  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id', dependent: :destroy
  has_many :followers, through: :reverses_of_relationship, source: :user

  has_many :favorites, dependent: :destroy
  has_many :favorite_post, through: :favorites, source: :micropost

  has_many :supports, dependent: :destroy
  has_many :support_record, through: :supports, source: :record

  # ----------Start of relationships----------
  def follow(other_user)
    relationships.find_or_create_by(follow_id: other_user.id) unless self == other_user
  end

  def unfollow(other_user)
    relationships = self.relationships.find_by(follow_id: other_user.id)
    relationships&.destroy
  end

  def following?(other_user)
    followings.include?(other_user)
  end

  def feed_microposts
    Micropost.where(user_id: following_ids)
  end
  # ----------End of relationships----------

  # ----------Start of favorites----------
  def favorite(micropost)
    favorites.find_or_create_by(micropost_id: micropost.id)
  end

  def unfavorite(micropost)
    favorite = favorites.find_by(micropost_id: micropost.id)
    favorite&.destroy
  end

  def favorite?(micropost)
    favorite_post.include?(micropost)
  end

  def favorite_microposts
    Micropost.where(id: favorite_post_ids)
  end
  # ----------End of favorites----------

  # ----------Start of supports----------
  def support(record)
    supports.find_or_create_by(record_id: record.id) if record.finished == false
  end

  def unsupport(record)
    support = supports.find_by(record_id: record.id)
    support&.destroy
  end

  def support?(record)
    support_record.include?(record)
  end
  # ----------End of Supports----------
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[
    show
    update
    edit_password
    update_password
    followings
    followers
    likes
    records
  ]
  before_action :set_count, only: %i[show likes records]
  before_action :require_user_logged_in, only: %i[show edit]
  before_action :correct_user, only: [:edit]

  def show
    @microposts = @user.microposts.order(id: :desc)
  end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_create)
    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  def update
    if @user.update(user_update)
      flash[:success] = 'ユーザー情報を更新しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザー情報を更新できませんでした'
      render :edit
    end
  end

  def followings
    @followings = @user.followings
  end

  def followers
    @followers = @user.followers
  end

  def likes
    @microposts = @user.favorite_microposts.order(id: :desc)
  end

  def records
    @records = @user.records.where(finished: true).order(id: :desc)
  end

  private

  def user_update
    params.require(:user).permit(:name, :email, :gender, :age, :img, :remove_img, :hide_gender, :hide_age, :hide_records)
  end

  def user_create
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :gender, :age, :img)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def set_count
    counts(@user)
  end

  def correct_user
    if User.find(params[:id]) != current_user
      @user = User.find(params[:id])
      redirect_to @user
    else
      @user = User.find(params[:id])
    end
  end
end

app/views/users/_user_info.html.erb
<div>
  <% if user.img.present? %>
    <%= image_tag user.img.url, class: 'profile-image-lg' %>
  <% else %>
    <%= image_tag 'default_image.png', class: 'profile-image-lg' %>
  <% end %>
  <h3><%= user.name %></h3>
  <% if user.hide_gender == true %>
    <p>非公開 | 
    <% if user.hide_age == true %>
      非公開
    <% else %>
      <%= user.age %>代
    <% end %></p>
  <% else %>
    <p><%= case user.gender 
          when 1
            '男性'
          when 2
            '女性'
          else
            'その他'
          end %> |  
    <% if user.hide_age == true %>
      非公開
    <% else %>
      <%= user.age %>代
    <% end %></p>
  <% end %>
  <div class='relationships'>
    <a><%= @count_followings %><%= link_to 'フォロー中', followings_user_path(user) %></a>
    <a><%= @count_followers %><%= link_to 'フォロワー', followers_user_path(user) %></a>
    <%= render 'relationships/follow_button', user: @user %>
  </div>
</div>
<div class='settings'>
  <% if current_user == user %>
    <%= link_to 'ユーザー設定', edit_user_path %>
    <%= link_to 'パスワード変更', edit_password_path %>
  <% end %>
</div>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul>
    <% users.each do |user| %>
      <li>
          <div class="card">
            <div class="user-bio">
              <% if user.img.present? %>
                <%= image_tag user.img.url, class: "profile-image-md" %>
              <% else %>
                <%= image_tag "default_image.png", class: "profile-image-md" %>
              <% end %>
              <%= link_to user.name, user_path(user), class: "name" %>  
              <div class="user-attributes">
                <% if user.hide_gender == true %>
                  <p>非公開 | 
                  <% if user.hide_age == true %>
                    非公開
                  <% else %>
                    <%= user.age %>代
                  <% end %></p>
                <% else %>
                  <p><%= case user.gender 
                        when 1
                          '男性'
                        when 2
                          '女性'
                        else
                          'その他'
                        end %> |  
                  <% if user.hide_age == true %>
                    非公開
                  <% else %>
                    <%= user.age %>代
                  <% end %></p>
                <% end %>
              </div>
            </div>
            <div class="follow-swtich">
              <% if current_user.following?(user) %>
                <%= form_with(model: current_user.relationships.find_by(follow_id: user.id), local: true, method: :delete) do |f| %>
                  <%= hidden_field_tag :follow_id, user.id %>
                  <%= f.submit "フォロー解除", class: 'btn unfollow' %>
                <% end %>
              <% else %>
                <%= form_with(model: current_user.relationships.build, local: true) do |f| %>
                  <%= hidden_field_tag :follow_id, user.id %>
                  <%= f.submit "フォロー", class: 'btn follow' %>
                <% end %>
              <% end %>
            </div>
          </div>
        </li>
    <% end %>
  </ul>
<% end %>

app/views/users/edit.html.erb
<div class='memo memo-md'><span class='masking-tape'></span>
  <h2 class='pagetitle'>ユーザー設定</h2>
    <div class='setting-form'>
      <%= form_with(model: @user, local: true) do |f| %>
        <%= render 'layouts/error_messages', model: @user %>
        <table>
          <tr>
            <th><%= f.label :name, 'ユーザー名' %></th>
            <td><%= f.text_field :name %></td>
          </tr>
          <tr>
            <th><%= f.label :email, 'メールアドレス' %></th>
            <td><%= f.email_field :email %></td>
          </tr>
          <tr>
            <th><%= f.label :gender, '性別' %></th>
            <td><%= f.select :gender, [['男', 1], ['女', 2], ['その他', 3]], { selected: 1 } %></td>
          </tr>
          <tr>
            <th><%= f.label :age, '年代' %></th>
            <td><%= f.select :age, ['10代', '20代', '30代', '40代', '50代', '60代', '70代', '80代', '90代' ] %></td>
          </tr>
          <tr>
            <th><%= f.label :hide_gender, '性別を非公開' %></th>
            <td><%= f.check_box :hide_gender %></td>
          </tr>
          <tr>
            <th><%= f.label :hide_age, '年代を非公開' %></th>
            <td><%= f.check_box :hide_age %></td>
          </tr>
          <tr>
            <th><%= f.label :hide_records, '勉強履歴を非公開' %></th>
            <td><%= f.check_box :hide_records %></td>
          </tr>
          <tr>
            <th>
              <% if @user.img.present? %>
                <%= image_tag @user.img.url, class: 'image'%>
              <% else %>
                <%= image_tag 'default_image.png', class: 'image' %>
              <% end %>
            </th>
            <td><%= f.file_field :img, id: :book_img %></td>
          </tr>
          <tr>
            <th><%= f.label :remove_img, '画像を削除' %></th>
            <td><%= f.check_box :remove_img %></td>
          </tr>
        </table>
        <div class="buttons">
          <%= f.submit '更新', class: "btn" %>
          <%= link_to '戻る', user_path(@user), class: "btn" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<div class='memo memo-md'><span class='masking-tape'></span>
  <h2 class='pagetitle'>フォロワー一覧</h2>
  <div class="user-lists scroll">
    <%= render "users/users", users: @followers %>
  </div>
</div>

app/views/users/followings.html.erb
<div class='memo memo-md'><span class='masking-tape'></span>
  <h2 class='pagetitle'>フォロー一覧</h2>
  <div class="user-lists scroll">
    <%= render "users/users", users: @followings %>
  </div>
</div>

app/views/users/likes.html.erb
<div class='memo memo-lg'><span class='masking-tape'></span>
  <div class='user-info'>
    <%= render 'user_info', user: @user %>
  </div>
  <div class='card-lists'>
    <ul class='nav nav-tabs nav-justified'>
      <li class='nav-item'><%= link_to 'つぶやき一覧', user_path(@user) %><%= @count_microposts %></li>
      <li class='nav-item'><%= link_to 'いいね一覧', likes_user_path(@user) %><%= @count_favorites %></li>
      <% if current_user == @user %>
        <li class='nav-item'><%= link_to '勉強履歴', records_user_path(@user) %><%= @count_records %></li>
      <% else %>
        <% unless @user.hide_records == true %>
          <li class='nav-item'><%= link_to '勉強履歴', records_user_path(@user) %><%= @count_records %></li>
        <% end %>
      <% end %>
    </ul>
    <div class='microposts scroll'>
      <%= render 'microposts/microposts', microposts: @microposts %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class='memo memo-md'><span class='masking-tape'></span>
<h2 class='pagetitle'>会員登録</h2>
  <div class='form'>
    <%= form_with(model: @user, local: true) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
      <div class='input-box'>
        <%= f.text_field :name %>
        <%= f.label :name, 'ユーザー名' %>
      </div>
      <div class='input-box'>
        <%= f.email_field :email %>
        <%= f.label :email, 'メールアドレス' %>
      </div>
      <div class='input-box'>
        <%= f.password_field :password %>
        <%= f.label :password, 'パスワード' %>
      </div>
      <div class='input-box'>
        <%= f.password_field :password_confirmation %>
        <%= f.label :password_confirmation, '確認用のパスワード' %>
      </div>
      <div class='select-box'>
        <%= f.select :gender, { '男': 1, '女': 2, 'その他': 3 }, { selected: 1 } %>
        <%= f.select :age, ['10代', '20代', '30代', '40代', '50代', '60代', '70代', '80代', '90代' ] %>
      </div>
      <div class='file-box'>
        <%= f.label :img, 'プロフィール画像' %>
        <%= f.file_field :img %>
      </div>
      <div class='submit'>
        <%= f.submit '登録' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/records.html.erb
<div class='memo memo-lg'><span class='masking-tape'></span>
  <div class='user-info'>
    <%= render 'user_info', user: @user %>
  </div>
  <div class='card-lists'>
    <ul class='nav nav-tabs nav-justified'>
      <li class='nav-item'><%= link_to 'つぶやき一覧', user_path(@user) %><%= @count_microposts %></li>
      <li class='nav-item'><%= link_to 'いいね一覧', likes_user_path(@user) %><%= @count_favorites %></li>
      <% if current_user == @user %>
        <li class='nav-item'><%= link_to '勉強履歴', records_user_path(@user) %><%= @count_records %></li>
      <% else %>
        <% unless @user.hide_records == true %>
          <li class='nav-item'><%= link_to '勉強履歴', records_user_path(@user) %><%= @count_records %></li>
        <% end %>
      <% end %>
    </ul>
    <div class='user-records scroll'>
        <%= render 'records/records', records: @records %>
      </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='memo memo-lg'><span class='masking-tape'></span>
  <div class='user-info'>
    <%= render 'user_info', user: @user %>
  </div>
  <div class='card-lists'>
    <ul class='nav nav-tabs nav-justified'>
      <li class='nav-item'><%= link_to 'つぶやき一覧', user_path(@user) %><%= @count_microposts %></li>
      <li class='nav-item'><%= link_to 'いいね一覧', likes_user_path(@user) %><%= @count_favorites %></li>
      <% if current_user == @user %>
        <li class='nav-item'><%= link_to '勉強履歴', records_user_path(@user) %><%= @count_records %></li>
      <% else %>
        <% unless @user.hide_records == true %>
          <li class='nav-item'><%= link_to '勉強履歴', records_user_path(@user) %><%= @count_records %></li>
        <% end %>
      <% end %>
    </ul>
    <div class='microposts scroll'>
      <%= render 'microposts/microposts', microposts: @microposts %>
    </div>
  </div>
</div>