config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  # サイトの使い方ページ
  get 'about', to: 'toppages#about'

  # ログイン機能
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # 簡単ログイン
  post 'easy_login', to: 'guest_sessions#test'

  # 勉強を始める
  get 'start', to: 'records#new'

  resources :users, only: %i[index show new edit create update] do
    member do
      get :followings
      get :followers
      get :likes
      get :records
    end
  end

  resources :microposts, only: %i[index create destroy] do
    member do
      get :following_posts
    end
  end

  resources :records, only: %i[index show new edit create] do
    member do
      get :stop
      get :restart
      get :finish
      get :result
    end
  end

  resources :supports, only: %i[create destroy] do
    collection do
      get :supporters
    end
  end

  resources :relationships, only: %i[create destroy]
  resources :favorites, only: %i[create destroy]
  resource :password, only: %i[show edit update]
end

app/models/record.rb
class Record < ApplicationRecord
  validates :label, length: { maximum: 30 }
  validates :start_time, presence: true

  belongs_to :user

  has_many :supports, dependent: :destroy
  has_many :supporter, through: :supports, source: :user

  def feed_records
    Record.where(finished: false)
  end

  def add_elapsed_time
    stop_time = Time.zone.now
    self.elapsed_time += stop_time.to_i - start_time.to_i
  end

  def stop
    add_elapsed_time
    self.start_time = Time.zone.now
    self.stopped = true
    save
  end

  def restart
    self.start_time = Time.zone.now
    self.stopped = false
    save
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :require_user_logged_in, only: [:new]
  before_action :set_record, only: %i[show stop restart result]
  before_action :show_validate, only: [:show]
  before_action :create_validate, only: [:new]

  def index
    @records = Record.where(finished: false)
  end

  def show; end

  def new
    @record = Record.new
  end

  def create
    @record = current_user.records.build(record_create)
    @record.start_time = Time.zone.now
    @record.elapsed_time = 0
    @record.stopped = false
    @record.finished = false
    if @record.save
      flash[:success] = '勉強を開始しました。'
      redirect_to records_path
    else
      flash.now[:danger] = '勉強を開始できませんでした。'
      render :new
    end
  end

  def stop
    @record.stop
    redirect_back(fallback_location: '/')
  end

  def restart
    @record.restart
    redirect_back(fallback_location: '/')
  end

  def finish
    finish_record
    render :result
  end

  def result; end

  private

  def set_record
    @record = Record.find(params[:id])
  end

  def record_create
    params.require(:record).permit(:label, :hide_support, :null_timer)
  end

  def show_validate
    if @record.finished
      flash[:danger] = '既に勉強を終了しています。'
      redirect_to action: :new
    end
  end

  def create_validate
    if current_user.records.where(finished: false).size >= 1
      flash[:danger] = '既に勉強を開始しています。'
      redirect_to action: :index
    end
  end
end

app/helpers/records_helper.rb
module RecordsHelper
  def support_counts(record)
    Support.where(record_id: record.id).count
  end
end

app/views/records/_records.html.erb
<ul>
  <% records.each do |record| %>
    <li>
      <div class='card'>
        <div class='user-bio'>
          <% if record.user.img.present? %>
            <%= image_tag record.user.img.url, class: "profile-image-md"  %>
          <% else %>
            <%= image_tag "default_image.png", class: "profile-image-md" %>
          <% end %>
          <%= link_to record.user.name, user_path(record.user), class: "name" %>
        </div>
        <div class="record-label">
          <p><%= record.label %></p>
        </div>
        <div class="record-bio">
          <p><%= Time.at(record.created_at).strftime("%Y-%m-%d") %> </p>
          <% unless record.null_timer == true %>
            <p><%= Time.at(record.elapsed_time).strftime("%H時%M分%S秒") %> </p>
          <% end %>
          <% unless record.hide_support == true %>
            <i class="fas fa-thumbs-up fa-lg"></i>
            <p class="support-counts"><%= support_counts(record) %></p>
          <% end %>
        </div>
      </div>
    </li>
  <% end %>
</ul>

app/views/records/_show.html.erb
<div class="studying_banner">
  <% if record.user.img.present? %>
    <%= image_tag record.user.img.url, class: "profile-image-md"  %>
  <% else %>
    <%= image_tag "default_image.png", class: 'profile-image-md' %>
  <% end %>
  <div class="study-menu">
    <% if record.stopped == false %>
      <%= link_to "一時停止", stop_record_path(record), class: "btn" %>
    <% else %>
      <%= link_to "再開", restart_record_path(record), class: "btn" %>
    <% end %>
    <%= link_to "終了", finish_record_path(record), data: {confirm: "本当に終了しますか？"}, class: "btn" %>
  </div>
  <div class="label">
    <p><%= record.label %></p>
  </div>
  <div class="yells">
    <% unless record.hide_support == true %>
      <i class="fas fa-thumbs-up fa-lg"></i>
      <%= link_to support_counts(record), supporters_supports_path %></p>
    <% end %>
  </div>
</div>

app/views/records/index.html.erb
<div class='memo memo-lg'><span class='masking-tape'></span>
  <div class="studying-people">
    <h1>勉強している人</h1>
    <% if @records.any? %>
      <p>仲間にエールを送りましょう!</p>
    <% else %>
      <p>現在勉強している人はいません</p>
    <% end %>
  </div>
  <div class="studying-records scroll">
    <ul>
      <% @records.each do |record| %>
        <li>
          <div class="card">
            <div class="user-bio">
              <% if record.user.img.present? %>
                <%= image_tag record.user.img.url, class: "profile-image-md"  %>
              <% else %>
                <%= image_tag "default_image.png", class: "profile-image-md" %>
              <% end %>
              <%= link_to record.user.name, user_path(record.user), class: "name" %>
              <div class="user-attributes">
                <% if record.user.hide_gender == true %>
                  <p>非公開 | 
                  <% if record.user.hide_age == true %>
                    非公開
                  <% else %>
                    <%= record.user.age %>代
                  <% end %></p>
                <% else %>
                  <p><%= case record.user.gender 
                        when 1
                          '男性'
                        when 2
                          '女性'
                        else
                          'その他'
                        end %> |  
                  <% if record.user.hide_age == true %>
                    非公開
                  <% else %>
                    <%= record.user.age %>代
                  <% end %></p>
                <% end %>
              </div>
            </div>
            <div class="record-label">
              <%= record.label %>
            </div>
            <% unless record.hide_support == true %>
              <div class="record-bio">
                <%= render "supports/support_button", record: record %>
              </div>
            <% end %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/records/new.html.erb
<div class="memo memo-sm"><span class='masking-tape'></span>
  <h2 class="pagetitle">勉強をはじめる</h2>
  <div class="study-new">
    <div class="form">
      <%= form_with(model: @record, local: true) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
        <div class="input-box">
          <%= f.label :label, "学習の内容や意気込みなど（30文字以内）" %>
          <%= f.text_area :label %>
        </div>
        <div class="check-box">
          <%= f.label :hide_support, "エールを表示しない" %>
          <%= f.check_box :hide_support %>
        </div>
        <div class="check-box">
          <%= f.label :null_timer, "時間を計測しない" %>
          <%= f.check_box :null_timer %>
        </div>
        <div class="submit">
          <%= f.submit "開始" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/records/result.html.erb
<div class="memo memo-sm"><span class='masking-tape'></span>
  <h2 class="pagetitle">おつかれさまです！</h2>
  <div class="result">
    <div class="label">
      <% if @record.label %>
        <%= @record.label %>
      <% else %>
        ラベルなし
      <% end %>
    </div>
    <% unless @record.null_timer == true %>
      <p class="elapsed_time">経過時間：<%= Time.at(@record.elapsed_time).strftime('%X') %></p>
    <% end %>
    <div class="yell">
      <% unless @record.hide_support == true %>
        <i class="fas fa-thumbs-up fa-lg"></i>
        <p class="support-counts"><%= support_counts(@record) %></p>
      <% end %>
    </div>
    <%= link_to "ホーム", records_path %>
  </div>
</div>