config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  # サイトの使い方ページ
  get 'about', to: 'toppages#about'

  # ログイン機能
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # 簡単ログイン
  post 'easy_login', to: 'guest_sessions#test'

  # 勉強を始める
  get 'start', to: 'records#new'

  resources :users, only: %i[index show new edit create update] do
    member do
      get :followings
      get :followers
      get :likes
      get :records
    end
  end

  resources :microposts, only: %i[index create destroy] do
    member do
      get :following_posts
    end
  end

  resources :records, only: %i[index show new edit create] do
    member do
      get :stop
      get :restart
      get :finish
      get :result
    end
  end

  resources :supports, only: %i[create destroy] do
    collection do
      get :supporters
    end
  end

  resources :relationships, only: %i[create destroy]
  resources :favorites, only: %i[create destroy]
  resource :password, only: %i[show edit update]
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    redirect_to @current_user if current_user
  end

  def about; end
end

app/views/toppages/_footer.html.erb
<p>© 2020 Inhome Study All rights reserved.	</p>

app/views/toppages/_header.html.erb
<nav class='navbar navbar-expand-sm navbar-light'>
  <div class='header-icon'>
    <% if logged_in? %>
      <%= link_to 'ホムスタ', records_path, class: 'icon' %> 
    <% else %>
      <%= link_to 'ホムスタ', root_path, class: 'icon' %> 
    <% end %>
  </div>
  
  <div class='header-menu'>
    <button type='button' class='navbar-toggler' data-toggle='collapse' data-target='#nav-bar' >
        <span class='navbar-toggler-icon'></span>
    </button>
    <div class='collapse navbar-collapse' id='nav-bar'>
      <ul class='navbar-nav'>
        <li><%= link_to 'ABOUT', about_path, class: 'nav-link' %></li>
        <li><%= link_to '勉強している人', records_path, class: 'nav-link' %></li>
        <% if logged_in? %>
          <% if studying? %>
            <li><%= link_to '勉強を終了する', finish_record_path(@record), data: {confirm: "本当に終了しますか？"}, class: 'nav-link' %></li>
          <% else %>
            <li><%= link_to '勉強を始める', start_path, class: 'nav-link' %></li>
          <% end %>
          <li><%= link_to 'タイムライン', microposts_path, class: 'nav-link' %></li>
          <li><%= link_to 'マイページ', user_path(current_user), class: 'nav-link' %></li>
          <% if studying? %>
            <li><%= link_to 'ログアウト', logout_path, method: :delete, data: {confirm: '勉強も終了しますか？'}, class: 'nav-link' %></li>
          <% else %>
            <li><%= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link' %></li>
          <% end %>
        <% else %>
          <li><%= link_to '会員登録', signup_path, class: 'nav-link' %></li>
          <li><%= link_to 'ログイン', root_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/toppages/about.html.erb
<div class='memo memo-lg'><span class='masking-tape'></span>
  <div class="about">
    <h1 class="title">ホムスタってなに？</h1>
    <p>自習学習をサポートするサービスです。</p>

    <h1 class="title">できること</h1>
    <h2 class="subtitle">勉強をはじめる</h2>
    <p>勉強を始めるときは開始ボタン、終わるときは終了ボタンを押すことで、時間を測りましょう。</p>
    <p>応援ボタンを押すと、他のユーザーにエールを送ることもできます。</p>
    <h2 class="subtitle">みんなとつながる</h2>
    <p>同じ志を持つ人をみつけたら、フォローすることができます。</p>
    <p>みんなとコミュニケーションをとって、切磋琢磨しましょう！</p>
  </div>
</div>

app/views/toppages/index.html.erb
<h1 class='introduction'>みんなと一緒に<br>勉強しましょう！</h1>
<div class='login_egg'>
  <div class='login-form form'>
    <h2>ログイン</h2>
    <%= form_with(url: login_path, scope: :session, local: true) do |f| %>
      <div class='input-box'>
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email %>
      </div>
      <div class='input-box'>
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password %>
      </div>
      <div class="submit">
        <%= f.submit 'ログイン' %>
      </div>
    <% end %>
    <%= link_to '簡単ログイン', easy_login_path, method: :post, class: 'easy-login' %>
  </div>
</div>