config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  # サイトの使い方ページ
  get 'about', to: 'toppages#about'

  # ログイン機能
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # 簡単ログイン
  post 'easy_login', to: 'guest_sessions#test'

  # 勉強を始める
  get 'start', to: 'records#new'

  resources :users, only: %i[index show new edit create update] do
    member do
      get :followings
      get :followers
      get :likes
      get :records
    end
  end

  resources :microposts, only: %i[index create destroy] do
    member do
      get :following_posts
    end
  end

  resources :records, only: %i[index show new edit create] do
    member do
      get :stop
      get :restart
      get :finish
      get :result
    end
  end

  resources :supports, only: %i[create destroy] do
    collection do
      get :supporters
    end
  end

  resources :relationships, only: %i[create destroy]
  resources :favorites, only: %i[create destroy]
  resource :password, only: %i[show edit update]
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  validates :content, presence: true, length: { maximum: 50 }
  belongs_to :user

  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites, source: :user
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]

  def index
    if logged_in?
      @micropost = current_user.microposts.build # form_with用
      @microposts = Micropost.order(id: :desc)
    end
  end

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = '投稿しました'
      redirect_to microposts_path
    else
      @microposts = Micropost.order(id: :desc)
      flash[:danger] = '投稿できませんでした'
      redirect_to microposts_path
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = '削除しました'
    redirect_back(fallback_location: root_path)
  end

  def following_posts
    @microposts = current_user.feed_microposts.order(id: :desc)
  end

  private

  def micropost_params
    params.require(:micropost).permit(:content)
  end

  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    redirect_to root_url unless @micropost
  end
end

app/views/microposts/_microposts.html.erb
<ul>
  <% microposts.each do |micropost| %>
    <li>
      <div class='card'>
        <div class='user-bio'>
          <% if micropost.user.img.present? %>
            <%= image_tag micropost.user.img.url, class: 'profile-image-md'  %>
          <% else %>
            <%= image_tag 'default_image.png', class: 'profile-image-md' %>
          <% end %>
          <%= link_to micropost.user.name, user_path(micropost.user), class: 'name' %>
        </div>
        <div class='micropost-content'>
          <p><%= micropost.content %></p>
        </div>
        <div class='micropost-bio'>
          <p><%= Time.at(micropost.created_at).strftime('%Y-%m-%d %H時%M分') %></p>
          <% if current_user == micropost.user %>
            <%= link_to ' | 削除', micropost, method: :delete, data: { confirm: 'You sure?' }, class: 'delete' %>
          <% end %>
          <% if current_user.favorite?(micropost) %>
            <%= form_with(model: current_user.favorites.find_by(micropost_id: micropost.id), local: true, method: :delete) do |f| %>
              <%= hidden_field_tag :favorite_id, micropost.id %>
              <%= f.button :type => 'submit' do %>
                <i class="fas fa-heart fa-lg like"></i>
              <% end %>
            <% end %>
          <% else %>
            <%= form_with(model: current_user.favorites.build, local: true) do |f| %>
              <%= hidden_field_tag :favorite_id, micropost.id %>
              <%= f.button :type => 'submit' do %>
                <i class="far fa-heart fa-lg yell"></i>
              <% end %>
            <% end %>
          <% end %>
          <p class='like-counts'><%= micropost.favorites.count %></p>
        </div>
      </div>
    </li>
  <% end %>
</ul>

app/views/microposts/following_posts.html.erb
<div class='memo memo-lg'><span class='masking-tape'></span>
  <div class='post-box'>
    <p class="guide">
      好きなことを50字以内で発信できます!
    </p>
    <%= form_with(model: @micropost, local: true) do |f| %>
      <%= f.text_area :content %>
      <%= f.submit 'Tweet!', class: 'tweet-btn' %>
    <% end %>
  </div>
  <div class='feed'>
    <ul class='nav nav-tabs nav-justified'>
      <li class='nav-item'><%= link_to 'すべて', microposts_path %></li>
      <li class='nav-item'><%= link_to 'フォロー', following_posts_micropost_path(@current_user) %></li>
    </ul>
    <div class="microposts scroll">
      <%= render 'microposts/microposts', microposts: @microposts %>
    </div>
  </div>
</div>

app/views/microposts/index.html.erb
<div class='memo memo-lg'><span class='masking-tape'></span>
  <div class='post-box'>
    <p class="guide">
      好きなことを50字以内で発信しましょう！
    </p>
    <%= form_with(model: @micropost, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <%= f.text_area :content %>
      <%= f.submit 'Tweet!', class: 'tweet-btn' %>
    <% end %>
  </div>
  <div class='feed'>
    <ul class='nav nav-tabs nav-justified'>
      <li class='nav-item'><%= link_to 'すべて', microposts_path %></li>
      <li class='nav-item'><%= link_to 'フォロー', following_posts_micropost_path(@current_user) %></li>
    </ul>
    <div class="microposts scroll">
      <%= render 'microposts/microposts', microposts: @microposts %>
    </div>
  </div>
</div>